# Generated by Django 5.2.7 on 2025-10-23 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('upload_type', models.CharField(choices=[('zip', 'ZIP File'), ('github', 'GitHub URL')], max_length=10)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('github_branch', models.CharField(default='main', max_length=100)),
                ('last_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('parsing', 'Parsing Code'), ('embedding', 'Generating Embeddings'), ('indexing', 'Indexing to Elasticsearch'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('total_files', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('project_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('chunk_type', models.CharField(max_length=50)),
                ('chunk_name', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('summary', models.TextField()),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('es_doc_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='repo_ingest.repository')),
            ],
            options={
                'ordering': ['file_path', 'start_line'],
            },
        ),
    ]
