# Generated by Django 5.2.7 on 2025-10-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='suggested_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='github_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='upload_type',
            field=models.CharField(choices=[('zip', 'ZIP File'), ('github', 'GitHub URL')], max_length=20),
        ),
    ]
